MODULE ThermalParametersModule

  IMPLICIT NONE
  PRIVATE

  INTEGER, PARAMETER, PUBLIC :: DP = KIND( 1.d0 )

  REAL(DP), PARAMETER, PUBLIC :: Pi = ACOS( - 1.0_DP )

  INTEGER, PARAMETER, PUBLIC :: nE = 1
  INTEGER, PARAMETER, PUBLIC :: nX = 1024
  INTEGER, PARAMETER, PUBLIC :: nY = 1
  INTEGER, PARAMETER, PUBLIC :: nZ = 1

  REAL(DP), PARAMETER, PUBLIC :: E_L = 0.0_DP
  REAL(DP), PARAMETER, PUBLIC :: E_R = 1.0_DP
  REAL(DP), PARAMETER, PUBLIC :: X_L = -10.0_DP
  REAL(DP), PARAMETER, PUBLIC :: X_R = 10.0_DP
  REAL(DP), PARAMETER, PUBLIC :: Y_L = 0.0_DP
  REAL(DP), PARAMETER, PUBLIC :: Y_R = 1.0_DP
  REAL(DP), PARAMETER, PUBLIC :: Z_L = 0.0_DP
  REAL(DP), PARAMETER, PUBLIC :: Z_R = 1.0_DP
  REAL(DP), PARAMETER, PUBLIC :: t_end = 1.024_DP
  REAL(DP), PARAMETER, PUBLIC :: C = 0.49_DP
  REAL(DP), PARAMETER, PUBLIC :: del = 1.0_DP
  
END MODULE ThermalParametersModule
